### ISSUE TITLE
Group Formation

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#1]
## Epic
As a user, I want to be able to create a travel group within the application. This ensures everyone's safety by knowing each other's locations and makes sure that decisions can be made collectively for the most optimal outing.

## User Stories
- [x] Invite Friends backend #32 
- [x] Invite Friends #2
- [x] Google Account Registration #3
- [x] Poll to Declare Leader #4
