### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#10]
## Epic
As a user, I should be able to influence my bar crawl schedule selection with my preferences when I decide to create it. A list of bars will be returned that can be added to the group as suggestions. Later, my friends in the group can vote for each suggested bar and influence the final bar crawl schedule. This ensures that there is much less of a chance that people visit a bar that is either an inconvenience to visit or not offering the services/products they are looking for. 

## User Stories
- [x] Filtering Bars by Google Ratings and Reviews #11
- [x] Filtering Bars by Distance #12
- [x] Filtering Bars by Price #13
