### ISSUE TITLE
Bar Selection

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#6]
## Epic
As a user, I would like to be able to select and create a bar crawl route based on majority decisions within a group. This makes sure that everyone contributes in creating a schedule that is mutually enjoyed.

## User Stories
- [x] Send the List of Bars From Search To Every Group Member #14
- [x] Create a Poll Accessible by Members #15
- [x] Timer for the Poll #16
- [x] App's Suggested Optimal Schedule #17
