### ISSUE TITLE
Transportation

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#7]
## Epic
As a user, I would like to have different options for transportation to have financial efficiency and travel freedom for the bar crawl.

## User Stories
- [x] Connection to Uber API for Traveling #23
- [x] Connection to Google API for Distances and Public Transit Schedules #24
- [x] Notification System for Departure Time Alerts #25
- [x] AI/Autonomous System That Suggests Optimal Transit To/From Bars #26
