### ISSUE TITLE
Event Editing 

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#8]
## Epic
As a user, I might not like some of the per-determined bars or may want to add in extra bars might not have been found using the filter functions. Therefore, I would want the power to manually edit the newly created schedule.

## User Stories
- [x] Group Schedule Viewer #20
- [x] Polling System for Group Decisions #21
- [x] Notification System to Alert the Group of Decisions #22
